CREATE TABLE [dbo].[Task]
(
	[TaskId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	[Title] NVARCHAR(256) NOT NULL,
	[Description] NVARCHAR(MAX),
	[CreationDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[CreatorId] UNIQUEIDENTIFIER NOT NULL,
	[DeadLine] DATETIME2
)
GO

ALTER TABLE [Task] ADD CONSTRAINT [FK_Task_Creator] FOREIGN KEY ([CreatorId])
	REFERENCES [User] ([UserId])
GO
